<?php
/**
 * @var $this Mage_Checkout_Block_Onepage_Billing
 */
$sDeliveryDate = '<input
	type="text"
	name="b2bprofessional[delivery_date]"
	value="' . $this->escapeHtml($this->getQuote()->getDeliveryDate()) . '"
	title="' . $this->__('Delivery Date') . '"
	class="input-text"
	id="b2bprofessional:delivery_date" />';

$this->setTemplate('persistent/checkout/onepage/billing.phtml');
$sHtml = $this->toHtml();
// replace field in the billing.phtml, so we don't have to rewrite full billing.phtml and this is a bit more upgrade safe
$iPosition = strpos($sHtml, '<div class="buttons-set" id="billing-buttons-container">');
echo substr($sHtml, 0, $iPosition) .
	$sDeliveryDate .
	substr($sHtml, $iPosition);
