<div class="col-set order-info-box">
	<div class="col">
		<div class="box">
			<div class="box-title">
				<h2><?php echo $this->__('Additional') ?></h2>
			</div>
			<div class="box-content">
				<?php
				$aData = $this->getB2BProfessionalVars();
				foreach ($aData as $sKey => $sValue) {
					?>
					<b><?php echo $this->__($sKey); ?></b> : <?php echo $sValue; ?> <br/>
				<?php } ?>
			</div>
		</div>
	</div>
</div>
