<?php /* @var $this Mage_Checkout_Block_Cart_Item_Renderer */ ?>
<?php
/*
 * Set and render the magento default template for checkout items
 */
$this->setTemplate('checkout/cart/sidebar/default.phtml');
$sCoreHtml = $this->renderView();
$iProductId = $this->getItem()->getProductId();
/*
 * Check the default html for
 *  - <span class="price">something</span>
 *  - replace with the B2B price message when cart is invalid
 */
/* @var $oB2BHelper Sitewards_B2BProfessional_Helper_Data */
$oB2BHelper = Mage::helper('b2bprofessional');
echo $oB2BHelper->replaceOnInvalidCart(
	array('@<span class="price"[^>]*?>.*?</span>@siu'),
	array($oB2BHelper->getPriceMessage()),
	$sCoreHtml,
	$iProductId
);
?>