<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="fieldset">
	<form method="POST" id="order_form" action="<?php echo $this->getUrl('checkout/cart/addmultiple'); ?>">
		<table>
			<thead>
				<tr>
					<th><?php echo $this->__('SKU'); ?></th>
					<th><?php echo $this->__('Name'); ?></th>
					<th><?php echo $this->__('Price'); ?></th>
					<th><?php echo $this->__('Quantity'); ?></th>
				</tr>
			</thead>
			<tbody>
				<tr class="product">
					<td><input type="text" name="sku[]" class="sku input-text" /></td>
					<td class="name"></td>
					<td class="price"></td>
					<td><input type="text" name="qty[]"  class="qty input-text" disabled="disabled" /></td>
				</tr>
			</tbody>
		</table>
		<input type="submit" />
	</form>
	<div class="invisible">
		<img class="loading" src="<?php echo $this->getSkinUrl('images/sitewards/loading.gif');?>" />
	</div>
</div>