<div class="box-left">
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Additional') ?></h4>
		</div>
		<div class="fieldset">
			<table cellspacing="0" class="form-list">
				<?php
				$aData = $this->getB2BProfessionalVars();
				foreach ($aData as $sKey => $sValue) {
					?>
					<tr>
						<td style="width:10%" class="label"><strong><?php echo Mage::helper('sales')->__($sKey) ?></strong></td>
						<td class="value"><?php echo $sValue; ?></td>
					</tr>
				<?php }
				?>
			</table>
		</div>
	</div>
</div>
<div class="clear"></div>